config/routes.rb
Rails.application.routes.draw do
	
	devise_for :users
	root to: "todo_lists#index"
	resources :todo_lists do
		member do
	     patch :complete
	    end
	end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	belongs_to :user

	validates :description, presence: true
	validate :date_cannot_be_in_the_past
	# validates :status, presence: true

  	def date_cannot_be_in_the_past
	    errors.add(:date, "can't be in the past") if
	      !date.blank? and date < Date.today
  	end


	scope :completed, -> {
		where(:status => true)
	}

	scope :todo, -> {
		where(:status => false)
	}

	scope :having_date_between, ->(start_date, end_date) { where(date: start_date..end_date) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todo_lists

  validate :password_complexity
  
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[a-z])(?=.*?[0-9]).{6,70}$/

    errors.add :password, 'Complexity requirement not met. Length should be 6-70 characters and include: 1 lowercase, 1 digit.'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  helper_method :date_from_parameters
  before_action :authenticate_user! , only: [:new]
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    if params[:search] && params[:search][:date].present?
      start_date, end_date = params[:search][:date].split(' - ')
      @todo_lists = TodoList.having_date_between(start_date, end_date)
    else
      @todo_lists = TodoList.all.order("date ASC")
    # @todo_lists = TodoList.all
    end
  end

  def date_from_parameters
    if params[:search].present?
      params[:search][:date]
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.build
    # @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  def complete

    # todo_lists.update_attribute(:status, true)
    
    redirect_to todo_lists_url, notice: 'Todo item completed.'
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully created.' }
        # format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        # format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description, :date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>
	

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">PX's Todolist</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                <% if !current_user %>
                  <li><%= link_to("register", new_user_registration_path) %> </li>
                  <li><%= link_to("log in", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("log out", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/flashes" %>
        <%= render "common/navbar" %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-todo_list">
  <!--   <div class="form-todo_list string optional">
        <%= form.label :title, :class => "string optional control-label" %>
        <%= form.text_field :title, :class => "string optional form-control" %>   
    </div> -->
    <div class="form-todo_list string optional">
        <%= form.label :description, :class => "string optional control-label" %>
        <%= form.text_area :description, :class => "string optional form-control" %>
    </div>
    <div class="form-todo_list string optional">
        <%= form.label :date, :class => "string optional control-label" %>
        <%= form.date_select :date, :class => "string optional form-control" %>
    </div>
    <div class="form-todo_list string optional">
        <%= form.label :due_time, :class => "string optional control-label" %>
<!--         <%= form.text_field :due_time, due_time: { behavior: 'timepicker' }, class: 'form-control' %> -->
        <%= form.text_field :due_time, :class => "string optional form-control" %>

    </div>
    <div class="form-todo_list string optional">
        <%= form.label :status, :class => "string optional control-label" %>
        <!-- <%= form.check_box :status %> -->
        <%= form.select(:status,  {'created' => false, 'done' => true} , {}, { :class => 'select' }) %>
     </div>
  </div>
  <div class="actions">
    <%= form.submit "Submit", class: 'btn btn-success' %>
  </div>
<!--   <div class='input-append bootstrap-timepicker-component' style='display: inline;'>
    <input class='dateselect-time input-small' type='text' data-time='12:45 PM'>
    <span class='add-on'><i class='icon-time'></i></span>
  </div>  -->
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>
<br>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Todo Lists</h1>

<%= link_to 'New Todo List', new_todo_list_path, class: 'btn btn-success' %>
<br>

<div>
<h2>Search Todo Lists</h2>
<%= form_for(:search, class: 'form-inline', url: todo_lists_path, method: :get) do |form| %>
  <div class="form-group">
    <%= form.label :date %>
    <%= form.text_field :date, class: 'form-control', data: { behavior: 'daterangepicker' }, value: date_from_parameters %>

  </div>
  <%= form.submit "Search", class: 'btn btn-success' %>
<% end %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <!-- <th>Title</th> -->
      <th>Todo</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.todo.each do |todo_list| %>
      <% if todo_list.user == current_user %>
        <tr>
          <!-- <td><%= todo_list.status %>created</td> -->
          <td>created</td>
  <!--         <td><%= link_to "Mark as Complete", complete_todo_list_path(todo_list), method: :patch %></td> -->
          <!-- <td><%= todo_list.title %></td> -->
          <td><%= todo_list.description %></td>
          <td><%= todo_list.date %></td>
          <!-- <td><%= link_to 'Show', todo_list %></td> -->
          <td><%= link_to 'Edit', edit_todo_list_path(todo_list), class: "btn btn-sm btn-default" %></td>
          <td><%= link_to 'Delete', todo_list, class: "btn btn-sm btn-default", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div>
<h1>Completed</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Todo</th>
      <!-- <th>Description</th> -->
      <th>Finish time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.completed.each do |todo_list| %>
      <% if todo_list.user == current_user %>
        <tr>
          <td><strike>done</strike></td>
          <!-- <td><strike><%= todo_list.title %></strike></td> -->
          <td><strike><%= todo_list.description %></strike></td>
          <td><strike><%= todo_list.updated_at %></strike></td>
          <!-- <td><%= link_to 'Show', todo_list %></td> -->
          <td><%= link_to 'Edit', edit_todo_list_path(todo_list), class: "btn btn-sm btn-default" %></td>
          <td><%= link_to 'Delete', todo_list, class: "btn btn-sm btn-default", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script>
  $(function(){
  $('[data-behavior=daterangepicker]').daterangepicker({
    locale: { format: 'DD/MM/YYYY'},
    cancelLabel: 'Clear'
  });

  $('[data-behavior=daterangepicker]').on('cancel.daterangepicker', function(){
    $(this).val(' ');
  });

});
</script>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>
<br>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @todo_list.date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo_list.status %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>